FROM quay.io/democracyworks/wildfly:9.0.2.Final-debug
MAINTAINER Democracy Works, Inc. <dev@democracy.works>

WORKDIR /opt/yourkit

USER root

RUN yum -y install bzip2
RUN curl -L -O https://www.yourkit.com/download/yjp-2016.02-b42-linux.tar.bz2
RUN tar -jxf yjp-2016.02-b42-linux.tar.bz2

USER jboss
