#!/bin/bash

if [[ -z $ADMIN_USERNAME || -z $ADMIN_PASSWORD ]]; then
  echo "ADMIN_USERNAME and ADMIN_PASSWORD must be set"
  exit 1
fi

touch /opt/jboss/wildfly/standalone/log/wildfly.log

/opt/jboss/wildfly/bin/add-user.sh $ADMIN_USERNAME $ADMIN_PASSWORD --silent

/opt/jboss/wildfly/bin/standalone.sh -Djboss.host.name=$HOSTNAME -b 0.0.0.0 -bmanagement 0.0.0.0 $@
