#!/bin/bash

if [[ -z $ADMIN_USERNAME || -z $ADMIN_PASSWORD ]]; then
  echo "ADMIN_USERNAME and ADMIN_PASSWORD must be set"
  exit 1
fi

touch /opt/jboss/wildfly/standalone/log/wildfly.log

/opt/jboss/wildfly/bin/add-user.sh $ADMIN_USERNAME $ADMIN_PASSWORD --silent

if [[ -e /opt/jboss/wildfly/newrelic/newrelic.jar ]]; then
  export JAVA_OPTS="$JAVA_OPTS -javaagent:/opt/jboss/wildfly/newrelic/newrelic.jar"
fi

if [[ -e /opt/yourkit/yjp-2016.02/bin/linux-x86-64/libyjpagent.so ]]; then
  export JAVA_OPTS="$JAVA_OPTS -agentpath:/opt/yourkit/yjp-2016.02/bin/linux-x86-64/libyjpagent.so=delay=10000"
fi

/opt/jboss/wildfly/bin/standalone.sh -Djboss.host.name=$HOSTNAME -b 0.0.0.0 -bmanagement 0.0.0.0 $NEWRELIC_ARG $@
